---
name: Yifen

author:
  facebook: anthonyeef
  twitter: anthonyeef
  github: anthonyeef
  linkedin: anthonyeef
  medium: anthonyeef
  email: anthonyeef@gmail.com

copyright:
  year: 2017
  name: Yifen

google-analytics:
  id: 'UA-59628523-1'

disqus:
  id: yifenwu

url: https://anthonyeef.github.io

baseurl: 

timezone: Asia/Shanghai

permalink: /:year-:month-:day/:title/

paginate: 5

paginate_path: /page:num/

markdown: kramdown

kramdown:
  input: GFM

nav:
- name: About
  url: /about
- name: Archive
  url: /archive
- name: Tags
  url: /tags
- name: Github
  url: https://github.com/anthonyeef

sass:
  sass_dir: _sass
  style: ':compressed'

defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post

gems:
- jekyll-seo-tag
- jekyll-paginate
- jekyll-admin
  
exclude:
- vendor
